### Auto MPG Dataset

In [10]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [11]:
#load from API
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
auto_mpg = fetch_ucirepo(id=9) 
  
# data (as pandas dataframes) 
X = auto_mpg.data.features 
y = auto_mpg.data.targets 
  
# metadata 
print(auto_mpg.metadata) 
  
# variable information 
print(auto_mpg.variables)

{'uci_id': 9, 'name': 'Auto MPG', 'repository_url': 'https://archive.ics.uci.edu/dataset/9/auto+mpg', 'data_url': 'https://archive.ics.uci.edu/static/public/9/data.csv', 'abstract': 'Revised from CMU StatLib library, data concerns city-cycle fuel consumption', 'area': 'Other', 'tasks': ['Regression'], 'characteristics': ['Multivariate'], 'num_instances': 398, 'num_features': 7, 'feature_types': ['Real', 'Categorical', 'Integer'], 'demographics': [], 'target_col': ['mpg'], 'index_col': ['car_name'], 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1993, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5859H', 'creators': ['R. Quinlan'], 'intro_paper': None, 'additional_info': {'summary': 'This dataset is a slightly modified version of the dataset provided in the StatLib library.  In line with the use by Ross Quinlan (1993) in predicting the attribute "mpg", 8 of the original instances were removed because they had unknown values for the "mpg" attribute.  The original dataset is available in the file "auto-mpg.data-original".\r\n\r\n"The data concerns city-cycle fuel consumption in miles per gallon, to be predicted in terms of 3 multivalued discrete and 5 continuous attributes." (Quinlan, 1993)', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '    1. mpg:           continuous\r\n    2. cylinders:     multi-valued discrete\r\n    3. displacement:  continuous\r\n    4. horsepower:    continuous\r\n    5. weight:        continuous\r\n    6. acceleration:  continuous\r\n    7. model year:    multi-valued discrete\r\n    8. origin:        multi-valued discrete\r\n    9. car name:      string (unique for each instance)', 'citation': None}}
           name     role         type demographic description units  \
0  displacement  Feature   Continuous        None        None  None
1           mpg   Target   Continuous        None        None  None
2     cylinders  Feature      Integer        None        None  None
3    horsepower  Feature   Continuous        None        None  None
4        weight  Feature   Continuous        None        None  None
5  acceleration  Feature   Continuous        None        None  None
6    model_year  Feature      Integer        None        None  None
7        origin  Feature      Integer        None        None  None
8      car_name       ID  Categorical        None        None  None

  missing_values
0             no
1             no
2             no
3            yes
4             no
5             no
6             no
7             no
8             no

In [13]:
type(X)

pandas.core.frame.DataFrame

In [14]:
type(y)

pandas.core.frame.DataFrame

In [15]:
X.head()

,displacement,cylinders,horsepower,weight,acceleration,model_year,origin
0,307.0,8,130.0,3504,12.0,70,1
1,350.0,8,165.0,3693,11.5,70,1
2,318.0,8,150.0,3436,11.0,70,1
3,304.0,8,150.0,3433,12.0,70,1
4,302.0,8,140.0,3449,10.5,70,1

In [17]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    392 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
dtypes: float64(3), int64(4)
memory usage: 21.9 KB

In [16]:
y.head()

    mpg
0  18.0
1  15.0
2  18.0
3  16.0
4  17.0

In [18]:
X.shape

(398, 7)

In [ ]:
df = pd.concat([X, y], axis=1) # X + y

df.head()

,displacement,cylinders,horsepower,weight,acceleration,model_year,origin,mpg
0,307.0,8,130.0,3504,12.0,70,1,18.0
1,350.0,8,165.0,3693,11.5,70,1,15.0
2,318.0,8,150.0,3436,11.0,70,1,18.0
3,304.0,8,150.0,3433,12.0,70,1,16.0
4,302.0,8,140.0,3449,10.5,70,1,17.0

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    392 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
 7   mpg           398 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [24]:
len(df)

398

In [25]:
398 * 0.95

378.09999999999997

In [23]:
threshold = len(df) * 0.95

threshold

378.09999999999997

In [27]:
help(pd.DataFrame.dropna)

Help on function dropna in module pandas.core.frame:

dropna(self, *, axis: 'Axis' = 0, how: 'AnyAll | lib.NoDefault' = <no_default>, thresh: 'int | lib.NoDefault' = <no_default>, subset: 'IndexLabel | None' = None, inplace: 'bool' = False, ignore_index: 'bool' = False) -> 'DataFrame | None'
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or sequence of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
    ...                    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
    ...                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
    ...                             pd.NaT]})
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis='columns')
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how='all')
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=['name', 'toy'])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    392 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
 7   mpg           398 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [29]:
df_cleaned = df.dropna(thresh=threshold, axis=1)

df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    392 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
 7   mpg           398 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [31]:
X['horsepower'].value_counts()

horsepower
150.0    22
90.0     20
88.0     19
110.0    18
100.0    17
         ..
61.0      1
93.0      1
148.0     1
152.0     1
82.0      1
Name: count, Length: 93, dtype: int64

In [32]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    392 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
dtypes: float64(3), int64(4)
memory usage: 21.9 KB

In [34]:
X['horsepower'].describe()

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [38]:
X['horsepower'].value_counts().head(1)

horsepower
150.0    22
Name: count, dtype: int64

In [46]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    392 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
 7   mpg           398 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [43]:
df_cleaned['horsepower'].isna().sum()

6

In [ ]:
median_horsepower = df_cleaned['horsepower'].median()

median_df = df_cleaned['horsepower'].fillna(median_horsepower)

median_df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    398 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
 7   mpg           398 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [ ]:
median_horsepower = df_cleaned['horsepower'].median()

df_cleaned['horsepower'] = df_cleaned['horsepower'].fillna(median_horsepower)

df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    398 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
 7   mpg           398 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [47]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  398 non-null    float64
 1   cylinders     398 non-null    int64
 2   horsepower    392 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
 6   origin        398 non-null    int64
 7   mpg           398 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [57]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X = df_cleaned.drop('mpg', axis=1)
y = df_cleaned['mpg']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=254, test_size=0.2)
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 318 entries, 47 to 326
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   displacement  318 non-null    float64
 1   cylinders     318 non-null    int64
 2   horsepower    318 non-null    float64
 3   weight        318 non-null    int64
 4   acceleration  318 non-null    float64
 5   model_year    318 non-null    int64
 6   origin        318 non-null    int64
dtypes: float64(3), int64(4)
memory usage: 19.9 KB

In [58]:
#instantiate model 
lr = LinearRegression()

lr.fit(X_train, y_train)

LinearRegression()

In [59]:
y_preds = lr.predict(X_test)

### MAE, RMSE, MSE 

'y_preds & y_test'

'y_preds & y_test'

In [54]:
y_test.head()

      mpg
108  20.0
4    17.0
169  20.0
171  24.0
143  26.0

In [56]:
y_preds

array([[27.37521796],
       [15.00685283],
       [22.50605476],
       [26.30127768],
       [26.33255592],
       [25.13265286],
       [30.78441979],
       [30.26964484],
       [25.83464049],
       [24.56583354],
       [16.12077458],
       [20.52021218],
       [13.18558171],
       [28.63744547],
       [36.32421552],
       [31.21537099],
       [15.16431106],
       [31.10591276],
       [24.9963428 ],
       [33.90255606],
       [15.02584481],
       [22.79015925],
       [29.22982149],
       [10.83331643],
       [28.45800963],
       [29.63310416],
       [22.81291542],
       [10.64048308],
       [33.59594905],
       [26.80296444],
       [23.66596852],
       [20.59776377],
       [30.50049412],
       [28.35589019],
       [16.61441076],
       [25.51086109],
       [22.53656225],
       [21.61140364],
       [20.58553111],
       [ 6.22526478],
       [29.24548687],
       [26.88612394],
       [22.05204868],
       [27.74046758],
       [32.24059764],
       [16.47353234],
       [28.14998147],
       [32.21842774],
       [ 9.08214543],
       [15.26036018],
       [31.88328155],
       [24.30092226],
       [27.60077869],
       [35.52869519],
       [21.71872351],
       [20.74227132],
       [21.17804203],
       [25.90912876],
       [32.50347299],
       [32.26092904],
       [31.55695117],
       [20.49859117],
       [11.4607483 ],
       [11.51106434],
       [21.44383117],
       [12.47152444],
       [27.39582834],
       [28.95072302],
       [19.48456645],
       [16.31274189],
       [26.84216775],
       [12.10505614],
       [31.1017676 ],
       [19.91107437],
       [31.00481876],
       [19.15470594],
       [18.18519496],
       [33.37922371],
       [24.02781399],
       [27.36570486]])

In [ ]:
#residuals -- differences betweeen y_preds & y_test

In [ ]:
""" 
1. Linearity between independent and dependent variables
2. homoscedasticity
3. Variance in residuals
4. Normality of Residuals
"""

In [61]:
df_cleaned[['weight', 'mpg']].describe()

            weight         mpg
count   398.000000  398.000000
mean   2970.424623   23.514573
std     846.841774    7.815984
min    1613.000000    9.000000
25%    2223.750000   17.500000
50%    2803.500000   23.000000
75%    3608.000000   29.000000
max    5140.000000   46.600000